Implementation cloudinary
TheRealCL/NON_VALUABLE_TOKENS pull request #6
Opened 2022-11-30 18:55 UTC by Joe-woods

voici mon form pour les new nvt

2022-11-30 19:00 UTC, MBOZAR approved these changes

2022-11-30 19:16 UTC, TheRealCL approved these changes
all good

2022-11-30 20:38 UTC, Joe-woods commented
update cloudinary

2022-12-01 15:45 UTC, Rox1610 requested changes
one action to be done

2022-12-01 15:45 UTC, Rox1610 commented on config/environments/development.rb
> +  config.active_storage.service = :cloudinary
same as to be done here:

# config/environments/production.rb
# [...]
config.active_storage.service = :cloudinary

2022-12-01 15:51 UTC, MBOZAR requested changes
re-push production.rb

2022-12-01 15:52 UTC, Rox1610 approved these changes
ok good to go

2022-12-01 15:53 UTC, MBOZAR approved these changes
yessir

2022-12-01 15:55 UTC, merged